//
//  DeviceDetect.h
//  MobileLooks
//
//  Created by Bret Timmins on 11/06/13
//
#ifndef __PICKER_SIZES_H__
#define __PICKER_SIZES_H__

#if 0
#define VPICKER_THUMB_WIDTH 128
#define VPICKER_THUMB_HEIGHT 128

#define VPICKER_THUMB_WIDTH_OFFSET 16
#define VPICKER_THUMB_HEIGHT_OFFSET 16

#define VPICKER_THUMB_LANDSCAPE_COLS 7
//#define VPICKER_THUMB_LANDSCAPE_ROWS 0

#define VPICKER_THUMB_PORTRAIT_COLS 5
//#define VPICKER_THUMB_LANDSCAPE_ROWS 0
#endif

#define VPICKER_THUMB_WIDTH 202 //200 188
#define VPICKER_THUMB_HEIGHT 204 //188

#define VPICKER_THUMB_WIDTH_OFFSET 4 //8
#define VPICKER_THUMB_HEIGHT_OFFSET 4 //8

#define VPICKER_THUMB_LANDSCAPE_COLS 5
#define VPICKER_THUMB_LANDSCAPE_ROWS 3

#define VPICKER_THUMB_PORTRAIT_COLS 3
#define VPICKER_THUMB_PORTRAIT_ROWS 5

#define VPICKER_SCROLL_LANDSCAPE_FRAME_X 0
#define VPICKER_SCROLL_LANDSCAPE_FRAME_Y 48
#define VPICKER_SCROLL_LANDSCAPE_FRAME_WIDTH 1024
#define VPICKER_SCROLL_LANDSCAPE_FRAME_HEIGHT 724-48
#define VPICKER_SCROLL_LANDSCAPE_FRAME_HEIGHT_ADJUST 30

#define VPICKER_SCROLL_PORTRAIT_FRAME_X 48+22
#define VPICKER_SCROLL_PORTRAIT_FRAME_Y 0
#define VPICKER_SCROLL_PORTRAIT_FRAME_WIDTH 768-48
#define VPICKER_SCROLL_PORTRAIT_FRAME_HEIGHT 980
#define VPICKER_SCROLL_PORTRAIT_FRAME_HEIGHT_ADJUST 30

#define VPICKER_THUMB_WIDTH_IPHONE 116 //200 188
#define VPICKER_THUMB_HEIGHT_IPHONE 116 //188

#define VPICKER_THUMB_WIDTH_OFFSET_IPHONE 4 //8
#define VPICKER_THUMB_HEIGHT_OFFSET_IPHONE 4 //8

#define VPICKER_THUMB_LANDSCAPE_COLS_IPHONE_4 4
#define VPICKER_THUMB_LANDSCAPE_COLS_IPHONE_5 5
#define VPICKER_THUMB_LANDSCAPE_ROWS_IPHONE 2

#define VPICKER_THUMB_PORTRAIT_COLS_IPHONE 2
#define VPICKER_THUMB_PORTRAIT_ROWS_IPHONE_4 4
#define VPICKER_THUMB_PORTRAIT_ROWS_IPHONE_5 5

#define VPICKER_SCROLL_LANDSCAPE_FRAME_X_IPHONE 0
#define VPICKER_SCROLL_LANDSCAPE_FRAME_Y_IPHONE 22
#define VPICKER_SCROLL_LANDSCAPE_FRAME_WIDTH_IPHONE_4 480
#define VPICKER_SCROLL_LANDSCAPE_FRAME_WIDTH_IPHONE_5 568
#define VPICKER_SCROLL_LANDSCAPE_FRAME_HEIGHT_IPHONE 320-22
#define VPICKER_SCROLL_LANDSCAPE_FRAME_HEIGHT_ADJUST_IPHONE 12

#define VPICKER_SCROLL_PORTRAIT_FRAME_X_IPHONE 34 //48+22
#define VPICKER_SCROLL_PORTRAIT_FRAME_Y_IPHONE 0
#define VPICKER_SCROLL_PORTRAIT_FRAME_WIDTH_IPHONE 320-34
#define VPICKER_SCROLL_PORTRAIT_FRAME_HEIGHT_IPHONE_4 436 //480
#define VPICKER_SCROLL_PORTRAIT_FRAME_HEIGHT_IPHONE_5 524 //568
#define VPICKER_SCROLL_PORTRAIT_FRAME_HEIGHT_ADJUST_IPHONE 12

#define VPICKER_TEXT_X 58
#define VPICKER_TEXT_Y 58

#define VPICKER_TEXT_X_IPHONE 28
#define VPICKER_TEXT_Y_IPHONE 28


#endif //__PICKER_SIZES_H__

